import { readFile } from "node:fs/promises";
import { resolve } from "node:path";

import {
  HARAJUKU_ACTIVE_ATTRIBUTE,
  HARAJUKU_ACTIVE_VALUE,
  HARAJUKU_STYLE_EXEMPT_ATTRIBUTE,
  HARAJUKU_STYLE_EXEMPT_VALUE,
} from "../src/mlink-video-controller/modules/harajuku-style-contract";

const HARAJUKU_STYLE_SOURCES = [
  "src/mlink-video-controller/modules/watch-harajuku-style-1.css",
  "src/mlink-video-controller/modules/watch-harajuku-style-2.css",
  "src/mlink-video-controller/modules/watch-harajuku-style-3.css",
  "src/mlink-video-controller/modules/watch-harajuku-style-4.css",
] as const;

export async function composeHarajukuStylesheet(
  projectRoot: string,
): Promise<string> {
  const parts = await Promise.all(
    HARAJUKU_STYLE_SOURCES.map((source) =>
      readFile(resolve(projectRoot, source), "utf8"),
    ),
  );
  const stylesheet = parts.join("\n");
  const panelStart = stylesheet.indexOf('  [aria-label="動画プレーヤー設定"],');
  const panelEnd = stylesheet.indexOf("\n  }", panelStart);
  const panelRule = stylesheet.slice(panelStart, panelEnd);
  const allowedOverrides = [
    "position: fixed !important;",
    "left: auto !important;",
    "top: 48px !important;",
  ];
  const importantCount = [...stylesheet.matchAll(/!important/gu)].length;
  if (
    panelStart < 0 ||
    panelEnd < 0 ||
    importantCount !== allowedOverrides.length ||
    allowedOverrides.some((declaration) => !panelRule.includes(declaration)) ||
    stylesheet.slice(0, panelStart).includes("!important") ||
    stylesheet.slice(panelEnd).includes("!important")
  ) {
    throw new Error(
      "Harajuku stylesheet permits only the official panel inline-position overrides",
    );
  }

  return [
    "/* Generated by scripts/build.ts from watch-harajuku-style-*.css. */",
    `@scope (:root[${HARAJUKU_ACTIVE_ATTRIBUTE}="${HARAJUKU_ACTIVE_VALUE}"]) to ([${HARAJUKU_STYLE_EXEMPT_ATTRIBUTE}="${HARAJUKU_STYLE_EXEMPT_VALUE}"]) {`,
    stylesheet.replaceAll(":root", ":scope"),
    "}",
    "",
  ].join("\n");
}
