import { readFile } from "node:fs/promises";
import { resolve } from "node:path";

import {
  HARAJUKU_ACTIVE_ATTRIBUTE,
  HARAJUKU_ACTIVE_VALUE,
} from "../src/mlink-video-controller/modules/harajuku-style-contract";

const HARAJUKU_STYLE_SOURCES = [
  "src/mlink-video-controller/modules/watch-harajuku-style-1.css",
  "src/mlink-video-controller/modules/watch-harajuku-style-2.css",
  "src/mlink-video-controller/modules/watch-harajuku-style-3.css",
  "src/mlink-video-controller/modules/watch-harajuku-style-4.css",
] as const;

export async function composeHarajukuStylesheet(
  projectRoot: string,
): Promise<string> {
  const parts = await Promise.all(
    HARAJUKU_STYLE_SOURCES.map((source) =>
      readFile(resolve(projectRoot, source), "utf8"),
    ),
  );
  const stylesheet = parts.join("\n");
  if (stylesheet.includes("!important")) {
    throw new Error(
      "Harajuku stylesheet must use the cascade instead of !important",
    );
  }

  return [
    "/* Generated by scripts/build.ts from watch-harajuku-style-*.css. */",
    `@scope (:root[${HARAJUKU_ACTIVE_ATTRIBUTE}="${HARAJUKU_ACTIVE_VALUE}"]) {`,
    stylesheet.replaceAll(":root", ":scope"),
    "}",
    "",
  ].join("\n");
}
