const EN = {
  bufferTitle: "Full video preload",
  bufferHelp:
    "Preloads the current quality into NicoCache_nl. Playback keeps its normal memory buffer. Stops on video or quality changes.",
  repeatTitle: "A–B repeat",
  pointA: "A · Start",
  pointB: "B · End",
  setCurrent: "Use current time",
  clear: "Clear",
  start: "Start",
  stop: "Stop",
  repeatStart: "Enable repeat",
  repeatStop: "Disable repeat",
  repeatHelp:
    "Enter seconds or m:ss. A and B apply to this video only. Pausing stays paused.",
  repeatHint: "Set A and B to repeat a section.",
  repeatReady: "Section ready",
  repeating: "Repeating A–B",
  invalidTime: "Enter a time within this video (seconds or m:ss).",
  invalidRange: "B must be at least 0.1 seconds after A.",
  bufferIdle: "Preload progress",
  buffering: "Preloading",
  complete: "Entire video cached",
  waiting: "Waiting for the video",
  unavailable: "Reload this Watch page to enable full video preload.",
  cacheUnconfirmed:
    "NicoCache_nl could not confirm the complete cache. Check disk space and the proxy, then retry.",
  repeatUnavailable:
    "Playback synchronization is not ready. Reload the Watch page if this persists.",
  loadError:
    "Preloading stopped. Check playback and the connection, then try again.",
};
type Copy = typeof EN;
const COPIES: Record<string, Partial<Copy>> = {
  ja: {
    bufferTitle: "全編先読み",
    bufferHelp:
      "現在の画質・音質でNicoCache_nlへ全編を先読みします。再生用バッファーは通常範囲のままです。動画・画質切り替えで停止します。",
    repeatTitle: "A-Bリピート",
    pointA: "A · 開始",
    pointB: "B · 終了",
    setCurrent: "現在位置を設定",
    clear: "クリア",
    start: "開始",
    stop: "中止",
    repeatStart: "リピート開始",
    repeatStop: "リピート解除",
    repeatHelp:
      "秒数または 分:秒 でも指定できます。この動画だけに適用し、一時停止中は再生を始めません。",
    repeatHint: "AとBを指定すると区間を繰り返せます。",
    repeatReady: "区間を設定済み",
    repeating: "A-Bリピート中",
    invalidTime: "動画内の時刻を秒数または 分:秒 で入力してください。",
    invalidRange: "BはAより0.1秒以上後に設定してください。",
    bufferIdle: "先読み進捗",
    buffering: "全編先読み中",
    complete: "全編キャッシュ済み",
    waiting: "動画の読み込み待ち",
    unavailable: "全編先読みを利用するには視聴ページを再読み込みしてください。",
    cacheUnconfirmed:
      "NicoCache_nlの完成キャッシュを確認できませんでした。空き容量とプロキシーの状態を確認して再試行してください。",
    repeatUnavailable:
      "公式プレイヤーとの同期を待っています。続く場合は視聴ページを再読み込みしてください。",
    loadError:
      "先読みを停止しました。動画の再生と通信状態を確認して再試行してください。",
  },
  zh: {
    bufferTitle: "全片预加载",
    repeatTitle: "A–B循环",
    pointA: "A · 开始",
    pointB: "B · 结束",
    setCurrent: "使用当前位置",
    clear: "清除",
    start: "开始",
    stop: "停止",
    repeatStart: "开启循环",
    repeatStop: "关闭循环",
  },
  hi: {
    bufferTitle: "पूरा वीडियो पहले लोड करें",
    repeatTitle: "A–B दोहराव",
    pointA: "A · शुरुआत",
    pointB: "B · अंत",
    setCurrent: "वर्तमान समय",
    clear: "साफ़ करें",
    start: "शुरू करें",
    stop: "रोकें",
    repeatStart: "दोहराव शुरू करें",
    repeatStop: "दोहराव रोकें",
  },
  es: {
    bufferTitle: "Precarga completa",
    repeatTitle: "Repetición A–B",
    pointA: "A · Inicio",
    pointB: "B · Fin",
    setCurrent: "Usar tiempo actual",
    clear: "Borrar",
    start: "Iniciar",
    stop: "Detener",
    repeatStart: "Activar repetición",
    repeatStop: "Desactivar repetición",
  },
  fr: {
    bufferTitle: "Préchargement intégral",
    repeatTitle: "Boucle A–B",
    pointA: "A · Début",
    pointB: "B · Fin",
    setCurrent: "Position actuelle",
    clear: "Effacer",
    start: "Démarrer",
    stop: "Arrêter",
    repeatStart: "Activer la boucle",
    repeatStop: "Désactiver la boucle",
  },
  ar: {
    bufferTitle: "تحميل الفيديو كاملاً مسبقاً",
    repeatTitle: "تكرار A–B",
    pointA: "A · البداية",
    pointB: "B · النهاية",
    setCurrent: "الوقت الحالي",
    clear: "مسح",
    start: "بدء",
    stop: "إيقاف",
    repeatStart: "تفعيل التكرار",
    repeatStop: "إيقاف التكرار",
  },
  pt: {
    bufferTitle: "Pré-carregar vídeo inteiro",
    repeatTitle: "Repetição A–B",
    pointA: "A · Início",
    pointB: "B · Fim",
    setCurrent: "Usar tempo atual",
    clear: "Limpar",
    start: "Iniciar",
    stop: "Parar",
    repeatStart: "Ativar repetição",
    repeatStop: "Desativar repetição",
  },
  bn: {
    bufferTitle: "সম্পূর্ণ ভিডিও প্রিলোড",
    repeatTitle: "A–B পুনরাবৃত্তি",
    pointA: "A · শুরু",
    pointB: "B · শেষ",
    setCurrent: "বর্তমান সময়",
    clear: "মুছুন",
    start: "শুরু",
    stop: "বন্ধ",
    repeatStart: "পুনরাবৃত্তি চালু",
    repeatStop: "পুনরাবৃত্তি বন্ধ",
  },
  ru: {
    bufferTitle: "Загрузка всего видео",
    repeatTitle: "Повтор A–B",
    pointA: "A · Начало",
    pointB: "B · Конец",
    setCurrent: "Текущее время",
    clear: "Очистить",
    start: "Начать",
    stop: "Остановить",
    repeatStart: "Включить повтор",
    repeatStop: "Выключить повтор",
  },
  ur: {
    bufferTitle: "پوری ویڈیو پہلے لوڈ کریں",
    repeatTitle: "A–B تکرار",
    pointA: "A · آغاز",
    pointB: "B · اختتام",
    setCurrent: "موجودہ وقت",
    clear: "صاف کریں",
    start: "شروع",
    stop: "بند",
    repeatStart: "تکرار شروع کریں",
    repeatStop: "تکرار بند کریں",
  },
};

export function getPlaybackToolsCopy(language: string): Copy {
  return { ...EN, ...COPIES[language.toLowerCase().split("-")[0]] };
}
