pip install mypy
pip install pywin32
pip install types-pywin32
pip install psutil
pip install types-psutil
pip install tkinterdnd2
pip install requests
pip install types-requests
pip install setuptools
pip install types-setuptools