name: Create Release Package

on:
  push:
    tags:
      - '#*'  # #から始まるタグ（例：#153）がプッシュされた時に実行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create Release Package
        run: |
          zip -r test_nlFilters_${{ github.ref_name }}.zip nlFilters/1[0-9][0-9]_* local/Custom*

      - name: Get Release Notes
        run: |
          # 198_ReleaseNotes.mdの内容をリリースノートとして使用
          cp nlFilters/198_ReleaseNotes.md release_notes.md

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: test_nlFilters_${{ github.ref_name }}.zip
          body_path: release_notes.md
          # 199_README.mdの内容をリポジトリのREADME.mdとしても使用
          generate_release_notes: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}