name: Create Release Package

on:
  push:
    tags:
      - '#*'  # #から始まるタグ（例：#153）がプッシュされた時に実行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create Release Package
        run: |
          zip -r test_nlFilters_${{ github.ref_name }}.zip nlFilters/1[0-9][0-9]_* local/Custom*

      - name: Create Release Notes
        run: |
          echo "## 変更点" > release_notes.md
          echo "" >> release_notes.md
          git log --pretty=format:"- %s" $(git describe --tags --abbrev=0 HEAD^)..HEAD >> release_notes.md

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: test_nlFilters_${{ github.ref_name }}.zip
          body_path: release_notes.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}