name: Create Release Package

on:
  push:
    tags:
      - '#*'  # #から始まるタグ（例：#153）がプッシュされた時に実行

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create Release Package
        run: |
          echo "Creating release package..."
          VERSION="${{ github.ref_name }}"
          VERSION="${VERSION/#\#/}"
          echo "Version: $VERSION"
          echo "Creating directories..."
          mkdir -p nlFilters/198 local/Custom
          touch nlFilters/198/test.txt local/Custom/test.txt
          touch nlFilters/198_ReleaseNotes.md
          zip -r "test_nlFilters_${VERSION}.zip" nlFilters/198 local/Custom nlFilters/198_ReleaseNotes.md

      - name: Create Release
        run: |
          REF_NAME="${{ github.ref_name }}"
          CLEAN_VERSION="${REF_NAME/#\#/}"
          echo "CLEAN_VERSION=${CLEAN_VERSION}" >> $GITHUB_ENV

      - name: Upload Release
        if: ${{ !env.IS_ACT && !env.ACT }}  # 本番環境でのみ実行
        uses: softprops/action-gh-release@v1
        with:
          files: test_nlFilters_${{ env.CLEAN_VERSION }}.zip
          body_path: nlFilters/198_ReleaseNotes.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}